[[redirects]]
  from = "/proxy/*"
  to = "https://15.165.84.55:8000/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/api/*"
  to = "carely-backend.site/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200